### PR TITLE
feat: Add query parameter to skip specific genres from m3u playlist

### PR DESCRIPTION
**Pull request by mohit-kothari**
## Description:

This PR adds query parameter to skip some genres from playlist. This is useful for filtering playlist to skip channels from specific genres.
E.g.: `&sg=Devotional,Educational,Lifestyle,Shopping`

## Background:
I am using this server to add live tv channels to my Jellyfin. This is working flawlessly for last 2 weeks. Only issue I have is, there are too many channels that I dont need. This query param helps filter out some of the channels.

### CODE REVIEW

**Comment by rabilrbl** [comment]
@mohit-kothari Thanks for the PR
Are show posters loading for you in jellyfin?

**Comment by rabilrbl** [comment]
Does it work along with `c=split` ?
Have you checked?

**Comment by mohit-kothari** [comment]
> @mohit-kothari Thanks for the PR
> Are show posters loading for you in jellyfin?

No, show posters are not working for me. I think it was because EPG has only path of image instead of complete URL (i.e. no hostname).

**Comment by mohit-kothari** [comment]
> Does it work along with `c=split` ?
> Have you checked?

Yes, we can use `sg` and `c=split` together. It is working.

**Comment by rabilrbl** [comment]
> > @mohit-kothari Thanks for the PR
> > Are show posters loading for you in jellyfin?
> 
> No, show posters are not working for me. I think it was because EPG has only path of image instead of complete URL (i.e. no hostname).

Yup realized that yesterday. If possible, can you please make a PR for that too? Otherwise leave it to me

**Comment by rabilrbl** [comment]
> > Does it work along with `c=split` ?
> > Have you checked?
> 
> Yes, we can use `sg` and `c=split` together. It is working.

Thanks

**Review by rabilrbl — APPROVED** [review]

**Pull request merged**
